spring.application.name=config_change_tracker

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n